### ISSUE TITLE
v1.9.0 breaks microphone support

### ISSUE THREAD

**Issue by alopix** [microsoft/cognitive-services-speech-sdk-js#125]
Use `AudioConfig.fromDefaultMicrophoneInput()` as the audio config for a connection and try listening once. It will crash with something like

```
Error: Uncaught [TypeError: Cannot read property 'send' of undefined]
        at reportException (…/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
        at Timeout.callback [as _onTimeout] (…/node_modules/jsdom/lib/jsdom/browser/Window.js:645:7)
        at ontimeout (timers.js:436:11)
        at tryOnTimeout (timers.js:300:5)
        at listOnTimeout (timers.js:263:5)
        at Timer.processTimers (timers.js:223:10) TypeError: Cannot read property 'send' of undefined
        at …/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.speech/src/common.speech/DialogServiceAdapter.ts:460:83
        at Timeout.callback [as _onTimeout] (…/node_modules/jsdom/lib/jsdom/browser/Window.js:643:19)
        at ontimeout (timers.js:436:11)
        at tryOnTimeout (timers.js:300:5)
        at listOnTimeout (timers.js:263:5)
        at Timer.processTimers (timers.js:223:10)
```

Works fine in v1.8.1 but is broken in the recently released v1.9.0.

**Comment by rhurey** [comment]
I believe the PR #126 addresses this.

**Comment by rhurey** [comment]
https://github.com/microsoft/cognitive-services-speech-sdk-js/releases/tag/v1.9.1 has the fix.
