### ISSUE TITLE
Can't import the package in NodeJS without `window is not defined` error

### ISSUE THREAD

**Issue by HazemAM** [microsoft/cognitive-services-speech-sdk-js#227]
Hello everyone.

I'm trying to use this package in a NodeJS environment (not a browser), but I can't import `microsoft-cognitiveservices-speech-sdk` (after installing via Yarn), without getting the following error:

```shell
./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/sdk/Audio/SpeakerAudioDestination.js:65
            if (typeof (AudioContext) !== "undefined" || typeof (window.webkitAudioContext) !== "undefined") {
                                                                 ^

ReferenceError: window is not defined
    at SpeakerAudioDestination.set [as format] (./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/sdk/Audio/SpeakerAudioDestination.js:65:66)
    at AudioOutputConfigImpl.set [as format] (./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/sdk/Audio/AudioConfig.js:301:41)
    at SynthesisAdapterBase.set [as audioOutputFormat] (./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.speech/SynthesisAdapterBase.js:212:57)
    at SpeechSynthesizer.implCommonSynthesizeSetup (./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/sdk/SpeechSynthesizer.js:275:44)
    at new SpeechSynthesizer (./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/sdk/SpeechSynthesizer.js:35:14)
    at Object.<anonymous> (./build/lib/transcription-services/microsoft.js:22:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (./build/lib/transcriper.js:24:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

### To Reproduce:
1. Add the package through Yarn or NPM
2. Import it using:
    ```js
    var sdk = require("microsoft-cognitiveservices-speech-sdk");
    ```

### Version of the Cognitive Services Speech SDK:
Latest (v1.13.1)

### Platform, Operating System, and Programming Language:
 - OS: macOS Catalina
 - Programming language: JavaScript (NodeJS)

**Comment by yulin-li** [comment]
Thanks for reaching out, seems it's a bug at our side. You can using `var synthesizer = new sdk.SpeechSynthesizer(speechConfig, null);` instead of `var synthesizer = new sdk.SpeechSynthesizer(speechConfig);` as a workaround.

**Comment by HazemAM** [comment]
Yep, this is the conclusion I reached too.

I tried a couple of ways, and the only way I found to get a `Buffer` response without having that error thrown, is to pass `null` instead of `undefined` as second argument to `SpeechSynthesizer`.
