### ISSUE TITLE
Unable to contact server. StatusCode: 1006, undefined Reason:  Unsupported type: object at: (shallow)

### ISSUE THREAD

**Issue by vlad-opencity** [microsoft/cognitive-services-speech-sdk-js#330]
OS: Mac 10.15.7, MacBook Pro (16-inch, 2019)
Environment: Node.js v12.20.0.
SDK: "microsoft-cognitiveservices-speech-sdk": "^1.15.1",

I have the following code:

    var speechConfig = sdk.SpeechConfig.fromSubscription("SUBSCRIPTIONKEY", "eastus");
    const synthesizer = new sdk.SpeechSynthesizer(speechConfig, undefined);
    let startTime = new Date();
    return synthesizer.speakTextAsync(
        body,
        result => {
            synthesizer.close();

It results in an error:
Unable to contact server. StatusCode: 1006, undefined Reason:  Unsupported type: object at: (shallow)

I stepped through the SDK. I can see that it attempts a connection over a WebSocket. The connection is successful. However, the connection returns an error event shortly after indicating: "Unsupported type: object at: (shallow)".

Also, you seem to have a bug in the key you're referencing for the url endpoint. Which generated the error string above.

Promise.reject("Unable to contact server. StatusCode: " + response.statusCode + ", " + this.privSynthesizerConfig.parameters.getProperty(Exports_2.PropertyId.SpeechServiceConnection_Endpoint) + " Reason: " + response.reason)

The "undefined" in Unable to contact server. StatusCode: 1006, undefined Reason:" is pointing to the wrong key. 

this.privSynthesizerConfig.parameters.getProperty(Exports_2.PropertyId.SpeechServiceConnection_Endpoint)

or at least on this version of the SDK.

Please HELP!

**Comment by vlad-opencity** [comment]
Update: Strangely enough, the standalone sample from the SDK works. But it does not work in my app!

Here is the call stack:

Update: Strangely enough, the standalone sample from the SDK works. But it does not work in my app!

Here is the call stack:

Error: Unsupported type: object at: (shallow)
    at Reporter.error (/src_root/node_modules/asn1.js/lib/asn1/base/reporter.js:76:11)
    at new EncoderBuffer (/src_root/node_modules/asn1.js/lib/asn1/base/buffer.js:86:21)
    at EncoderBuffer.<anonymous> (/src_root/node_modules/asn1.js/lib/asn1/base/buffer.js:70:16)
    at Array.map (<anonymous>)
    at new EncoderBuffer (/src_root/node_modules/asn1.js/lib/asn1/base/buffer.js:68:24)
    at DERNode.createEncoderBuffer [as _createEncoderBuffer] (/src_root/node_modules/asn1.js/lib/asn1/base/node.js:477:10)
    at DERNode.encode [as _encodeValue] (/src_root/node_modules/asn1.js/lib/asn1/base/node.js:545:20)
    at DERNode.encode [as _encode] (/src_root/node_modules/asn1.js/lib/asn1/base/node.js:485:21)
    at DERNode.encode [as _encodeValue] (/src_root/node_modules/asn1.js/lib/asn1/base/node.js:500:30)
    at DERNode.encode [as _encode] (/src_root/node_modules/asn1.js/lib/asn1/base/node.js:485:21)
    at CertID.encode (/src_root/node_modules/asn1.js/lib/asn1/encoders/der.js:22:20)
    at Entity.encode (/src_root/node_modules/asn1.js/lib/asn1/api.js:60:32)
    at Object.generate (/src_root/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/external/ocsp/ocsp/request.js:61:29)
    at Function.<anonymous> (/src_root/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/CertChecks.js:167:76)
    at step (/src_root/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/CertChecks.js:65:23)
    at Object.next (/src_root/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/CertChecks.js:46:53)
    at fulfilled (/src_root/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/CertChecks.js:37:58)

It's dying in this asn1 library. 

buffer.js:
function EncoderBuffer(value, reporter) {
  if (Array.isArray(value)) {
    this.length = 0;
    this.value = value.map(function(item) {
      if (!(item instanceof EncoderBuffer))
        item = new EncoderBuffer(item, reporter);
      this.length += item.length;
      return item;
    }, this);
  } else if (typeof value === 'number') {
    if (!(0 <= value && value <= 0xff))
      return reporter.error('non-byte EncoderBuffer value');
    this.value = value;
    this.length = 1;
  } else if (typeof value === 'string') {
    this.value = value;
    this.length = Buffer.byteLength(value);
  } else if (Buffer.isBuffer(value)) {
    this.value = value;
    this.length = value.length;
  } else {
    return reporter.error('Unsupported type: ' + typeof value); // Here is where the error string comes from
  }
}

The value parameter in this context is: 

{"length":9,"value":[{"value":{"type":"Buffer","data":[48,7]},"length":2},{"length":7,"value":[{"length":7,"value":[{"value":{"type":"Buffer","data":[6,5]},"length":2},{"value":{"type":"Buffer","data":[43,14,3,2,26]},"length":5}]}]}]}

I can see it's an "EncodedBuffer", which activates the else case above. Any ideas??

**Comment by vlad-opencity** [comment]
Ok problem solved. I didn't explicitly include asn1 in to my project. But somehow version 4.7.x was being installed. The sample installs a much newer version of this library: 5.4.1. I was able to resolve the issue by explicitly requiring version 5.4.1.

Thanks!

**Comment by yulin-li** [comment]
Thanks @vlad-opencity!
