### ISSUE TITLE
util could not be found within the project.

### ISSUE THREAD

**Issue by Athony1225** [microsoft/cognitive-services-speech-sdk-js#387]
error: Error: Unable to resolve module util from /Users/pjlincoln/react_native_pjlincoln/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/external/ocsp/ocsp/agent.js: util could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  3 | var ocsp = require('../ocsp');
  4 |
> 5 | var util = require('util');
    |                     ^
  6 | var http = require('http');
  7 | var https = require('https');
  8 | var rfc5280 = require('asn1.js-rfc5280');
    at ModuleResolver.resolveDependency (/Users/pjlincoln/react_native_pjlincoln/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:191:15)
    at DependencyGraph.resolveDependency (/Users/pjlincoln/react_native_pjlincoln/node_modules/metro/src/node-haste/DependencyGraph.js:353:43)
    at Object.resolve (/Users/pjlincoln/react_native_pjlincoln/node_modules/metro/src/lib/transformHelpers.js:271:42)
    at resolve (/Users/pjlincoln/react_native_pjlincoln/node_modules/metro/src/DeltaBundler/traverseDependencies.js:571:33)
    at /Users/pjlincoln/react_native_pjlincoln/node_modules/metro/src/DeltaBundler/traverseDependencies.js:587:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/pjlincoln/react_native_pjlincoln/node_modules/metro/src/DeltaBundler/traverseDependencies.js:586:33)
    at /Users/pjlincoln/react_native_pjlincoln/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/pjlincoln/react_native_pjlincoln/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)

**Comment by Athony1225** [comment]
my project is react-native , use JavaScript sdk.
npm version is 6.14.4

**Comment by glharper** [comment]
@Athony1225 You need to add the node-libs-react-native library to your project as a dependency. See [this repo](https://github.com/microsoft/cognitive-services-sdk-react-native-example) for a working example using react-native.
