### ISSUE TITLE
Error: crypto.getRandomValues() not supported.

### ISSUE THREAD

**Issue by caizt16** [microsoft/cognitive-services-speech-sdk-js#473]
The code that triggers the bug:

```
const getRecognizer = async () => {
        const audioConfig = AudioConfig.fromMicrophoneInput();
        const speechConfig = SpeechConfig.fromSubscription(Keys.speech2text, 'eastus');
        speechConfig.speechRecognitionLanguage = 'en-US';
        return new SpeechRecognizer(speechConfig, audioConfig);
    }
```

When I tried to initialize `AudioConfig` or `SpeechConfig` in React Native, the error occurs:

```
Error: Requiring module "node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/microsoft.cognitiveservices.speech.sdk.js", 
which threw an exception: Error: crypto.getRandomValues() not supported. 
See https://github.com/uuidjs/uuid#getrandomvalues-not-supported
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
```

I followed the instruction `See https://github.com/uuidjs/uuid#getrandomvalues-not-supported` 
and the documentation indicates that:

```
Note: If you are using Expo, you must be using at least react-native-get-random-values@1.5.0 and expo@39.0.0.
```

Sure, I am using Expo, with the correct version:

```
"expo": "~44.0.0",
"react-native-get-random-values": "^1.7.2",
```

So I think the error is something to do with the SDK, could you help check the bug?
Thanks!

**Comment by glharper** [comment]
@caizt16 Thanks for using Speech SDK and writing this issue up. Please see [this SO question](https://stackoverflow.com/questions/61169746/crypto-getrandomvalues-not-supported). The 'react-native-get-random-values' library should be imported in your app before our library is imported. We have an example repo integrating with react-native [here](https://github.com/microsoft/cognitive-services-sdk-react-native-example/tree/main), with this fix added.

**Comment by olverarce01** [comment]
i have the next error: TypeError: undefined is not a function
TypeError: undefined is not a function
    at getRandomBase64 (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:137801:65)
    at getRandomValues (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:137818:33)
    at rng (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:138485:27)
    at v4 (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:138841:63)
    at createGuid (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:138317:21)
    at createNoDashGuid (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:138321:22)
    at SpeakerAudioDestination (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:153029:89)
    at anonymous (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:142751:77)
    at anonymous (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:142755:52)
    at speechAzure (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:137743:89)
    at alertFunction (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:135226:36)
    at ?anon_0_ (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:135307:41)
    at next (native)
    at asyncGeneratorStep (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4641:26)
    at _next (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4660:29)
    at anonymous (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4665:14)
    at tryCallTwo (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4657:25)
    at _performTransitionSideEffects (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:61822:22)
    at _receiveSignal (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:61778:45)
    at onResponderRelease (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:61645:34)
    at apply (native)
    at invokeGuardedCallbackProd (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:62230:21)
    at apply (native)
    at invokeGuardedCallback (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:62316:42)
    at apply (native)
    at invokeGuardedCallbackAndCatchFirstError (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:62319:36)
    at executeDispatch (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:62383:48)
    at executeDispatchesInOrder (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:62400:26)
    at executeDispatchesAndRelease (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:63506:35)
    at executeDispatchesAndReleaseTopLevel (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:63513:43)
    at forEach (native)
    at forEachAccumulated (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:62842:22)
    at runEventsInBatch (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:63524:27)
    at runExtractedPluginEventsInBatch (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:63583:25)
    at anonymous (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:63564:42)
    at batchedUpdates$1 (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:74154:20)
    at batchedUpdates (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:63495:36)
    at _receiveRootNodeIDEvent (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:63563:23)
    at receiveTouches (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:63606:34)
    at apply (native)
    at __callFunction (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:2826:36)
    at anonymous (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:2587:31)
    at __guard (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:2777:15)
    at callFunctionReturnFlushedQueue (http://192.168.237.67:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:2586:21)
