### ISSUE TITLE
SpeakerAudioDestination -> privAudio undefined for volume get & set

### ISSUE THREAD

**Issue by calinalexandru** [microsoft/cognitive-services-speech-sdk-js#476]
Hello there,
It seems to be an issue in **SpeakerAudioDestination** class, as you can call methods (getters and setters) like **volume** & **mute()**, while **this.privAudio** does not necessarily need to be defined. Anyway, this will obviously result in an uncaught error.

Also, is there any way the community can contribute to this respo? I would like to make few PRs
Thank you.

**Comment by glharper** [comment]
@calinalexandru Thanks for writing this up and using Speech SDK, there should be a PR for this next week.

For community PRs, submit one and my team (or myself) will take a look. This particular issue seems relatively straightforward if you'd like a credit in the notes for the next release. :-)

**Comment by calinalexandru** [comment]
@glharper 
No credits are necessary, I was just a bit confused about whether the community can contribute. I found several other things which I think are worth changing.
Currently, I'm trying to build the project locally by following the readme and this happens:
`
❯ npm run build

> microsoft-cognitiveservices-speech-sdk@1.18.1-alpha.0.1 build
> gulp compress && gulp build2015

/Users/calin/ilie/opensource/cognitive-services-speech-sdk-js/node_modules/string-width/index.js:2
var stripAnsi = require('strip-ansi');
                ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/calin/ilie/opensource/cognitive-services-speech-sdk-js/node_modules/string-width/node_modules/strip-ansi/index.js from /Users/calin/ilie/opensource/cognitive-services-speech-sdk-js/node_modules/string-width/index.js not supported.
Instead change the require of /Users/calin/ilie/opensource/cognitive-services-speech-sdk-js/node_modules/string-width/node_modules/strip-ansi/index.js in /Users/calin/ilie/opensource/cognitive-services-speech-sdk-js/node_modules/string-width/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/calin/ilie/opensource/cognitive-services-speech-sdk-js/node_modules/string-width/index.js:2:17)
    at Object.<anonymous> (/Users/calin/ilie/opensource/cognitive-services-speech-sdk-js/node_modules/yargs/lib/usage.js:3:21)
    at Object.<anonymous> (/Users/calin/ilie/opensource/cognitive-services-speech-sdk-js/node_modules/yargs/yargs.js:7:15)
    at Object.<anonymous> (/Users/calin/ilie/opensource/cognitive-services-speech-sdk-js/node_modules/yargs/index.js:4:15)
    at Object.<anonymous> (/Users/calin/ilie/opensource/cognitive-services-speech-sdk-js/node_modules/gulp/node_modules/gulp-cli/index.js:6:13)
    at Object.<anonymous> (/Users/calin/ilie/opensource/cognitive-services-speech-sdk-js/node_modules/gulp/bin/gulp.js:3:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v17.2.0
`
any ideas?

**Comment by dargilco** [comment]
@calinalexandru I had an issue a couple of weeks ago building the project. I forget what the error was, but doing the following fixed the issue:
- updating both node and npm to latest version (not sure if that was required)
- running "npm ci" instead of "npm install"

**Comment by calinalexandru** [comment]
@dargilco thx for your reply; it seems that using npm ci gives me a different error.

I'm running these versions
```
❯ node -v
v17.2.0
❯ npm -v
8.1.4
❯ uname
Darwin
❯ sw_vers
ProductName:	macOS
ProductVersion:	12.1
BuildVersion:	21C52
```

running npm ci
```
❯ npm ci
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> microsoft-cognitiveservices-speech-sdk@1.18.1-alpha.0.1 preinstall
> npm install --package-lock-only --ignore-scripts --no-audit && npx npm-force-resolutions


up to date in 911ms

40 packages are looking for funding
  run `npm fund` for details

> microsoft-cognitiveservices-speech-sdk@1.18.1-alpha.0.1 prepare
> npm run build


> microsoft-cognitiveservices-speech-sdk@1.18.1-alpha.0.1 build
> gulp compress && gulp build2015

[14:10:59] Using gulpfile ~/ilie/opensource/microsoft-cognitive-services-speech-sdk-js/gulpfile.js
[14:10:59] Starting 'compress'...
[14:10:59] Starting 'bundle'...
[14:10:59] Starting 'build'...
[14:10:59] Starting 'build'...
Warning: The 'no-floating-promises' rule requires type information.
[14:11:06] Finished 'build' after 7.54 s
[14:11:06] Starting '<anonymous>'...
[14:11:06] Finished '<anonymous>' after 12 ms
[14:11:06] Finished 'build' after 7.55 s
[14:11:06] Starting 'bundle'...
[14:11:06] 'bundle' errored after 243 ms
[14:11:06] Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/calin/ilie/opensource/microsoft-cognitive-services-speech-sdk-js/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/calin/ilie/opensource/microsoft-cognitive-services-speech-sdk-js/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/calin/ilie/opensource/microsoft-cognitive-services-speech-sdk-js/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/calin/ilie/opensource/microsoft-cognitive-services-speech-sdk-js/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/calin/ilie/opensource/microsoft-cognitive-services-speech-sdk-js/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/calin/ilie/opensource/microsoft-cognitive-services-speech-sdk-js/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/calin/ilie/opensource/microsoft-cognitive-services-speech-sdk-js/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/calin/ilie/opensource/microsoft-cognitive-services-speech-sdk-js/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
[14:11:06] 'bundle' errored after 7.79 s
[14:11:06] 'compress' errored after 7.8 s
npm ERR! code 1
npm ERR! path /Users/calin/ilie/opensource/microsoft-cognitive-services-speech-sdk-js
npm ERR! command failed
npm ERR! command sh -c npm run build

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/calin/.npm/_logs/2022-02-19T12_11_06_884Z-debug.log
```

**Comment by dargilco** [comment]
Speech SDK 1.21 was release. See release notes: https://docs.microsoft.com/azure/cognitive-services/speech-service/releasenotes?tabs=speech-sdk#speech-sdk-1210-april-2022-release

**Comment by calinalexandru** [comment]
Great, thank you.
I see you updated the NPM package, but didn't push the tags to GitHub. Is there a reason for that? I wanted to see the diffs clearly.
