### ISSUE TITLE
The import order of `SpeechConfig` and `SpeechSynthesizer` causes error when using webpack as the project bundler.

### ISSUE THREAD

**Issue by Spedoske** [microsoft/cognitive-services-speech-sdk-js#505]
## Describe the bug
The import order of `SpeechConfig` and `SpeechSynthesizer` causes error when using webpack as the project bundler.

**The problem may be caused by webpack.**
## To Reproduce
run
```
npx create-react-app baz --template typescript && cd baz
npm install microsoft-cognitiveservices-speech-sdk
```

add the following code to `src/index.tsx`.
```
--- a/src/index.tsx
+++ b/src/index.tsx
@@ -4,6 +4,13 @@ import './index.css';
 import App from './App';
 import reportWebVitals from './reportWebVitals';

+import {SpeechConfig,SpeechSynthesizer} from "microsoft-cognitiveservices-speech-sdk";
+let foo: SpeechSynthesizer | null = null;
+
+function bar(key: string, region: string): void {
+    foo = new SpeechSynthesizer(SpeechConfig.fromSubscription(key, region), undefined)
+}
+
 ReactDOM.render(
   <React.StrictMode>
     <App />
```

run
```
npm run start
```

There is a problem in the console of the browser when visiting `localhost:3000`.
```
CognitiveTokenAuthentication.ts:10 Uncaught ReferenceError: Cannot access 'ConnectionFactoryBase' before initialization
    at Module.ConnectionFactoryBase (CognitiveTokenAuthentication.ts:10:1)
    at Module../node_modules/microsoft-cognitiveservices-speech-sdk/distrib/es2015/src/common.speech/IntentConnectionFactory.js (IntentConnectionFactory.ts:25:1)
    at Module.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at Module../node_modules/microsoft-cognitiveservices-speech-sdk/distrib/es2015/src/common.speech/Exports.js (EnumTranslation.ts:11:1)
    at Module.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at Module../node_modules/microsoft-cognitiveservices-speech-sdk/distrib/es2015/src/common.speech/ConnectionFactoryBase.js (CognitiveTokenAuthentication.ts:10:1)
```

## Versions
```
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.2",
    "@testing-library/react": "^12.1.4",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.4.1",
    "@types/node": "^16.11.26",
    "@types/react": "^17.0.41",
    "@types/react-dom": "^17.0.14",
    "microsoft-cognitiveservices-speech-sdk": "^1.20.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "5.0.0",
    "typescript": "^4.6.2",
    "web-vitals": "^2.1.4"
  },
```

## Platform, Operating System, and Programming Language
OS: Windows
Hardware - x86
Programming language: JavaScript,
Browser: Chrome

## Additional context
There is no problem when adding imports in the following way.
```
--- a/src/index.tsx
+++ b/src/index.tsx
@@ -4,6 +4,14 @@ import './index.css';
 import App from './App';
 import reportWebVitals from './reportWebVitals';

+import {SpeechConfig} from "microsoft-cognitiveservices-speech-sdk";
+import {SpeechSynthesizer} from "microsoft-cognitiveservices-speech-sdk";
+let foo: SpeechSynthesizer | null = null;
+
+function bar(key: string, region: string): void {
+    foo = new SpeechSynthesizer(SpeechConfig.fromSubscription(key, region), undefined)
+}
+
 ReactDOM.render(
   <React.StrictMode>
     <App />
```

**Comment by glharper** [comment]
@Spedoske I'm not seeing anything actionable here in our library, we can't do anything about the order/method webpack handles dependencies and their modules.
