### ISSUE TITLE
[Bug]: Cannot access 'ConnectionFactoryBase' before initialization

### ISSUE THREAD

**Issue by sorressean** [microsoft/cognitive-services-speech-sdk-js#772]
### What happened?

I am working on an app that will use this library. I receive this error but am unsure what needs to initialize or what the order may be. I found similar issues and wanted to raise this here.
Here is the full stacktrace:

ERROR
Cannot access 'ConnectionFactoryBase' before initialization
ReferenceError: Cannot access 'ConnectionFactoryBase' before 
initialization
at Module.ConnectionFactoryBase (http://192.168.88.76:3000/static/js/bundle.js:74034:68)
at ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.speech/IntentConnectionFactory.js (http://192.168.88.76:3000/static/js/bundle.js:75615:94)<BR>at options.factory 
(http://192.168.88.76:3000/static/js/bundle.js:95311:31)
at __webpack_require__ (http://192.168.88.76:3000/static/js/bundle.js:94734:33)
at fn (http://192.168.88.76:3000/static/js/bundle.js:94968:21)
at ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.speech/Exports.js (http://192.168.88.76:3000/static/js/bundle.js:75422:85)
at options.factory (http://192.168.88.76:3000/static/js/bundle.js:95311:31)
at __webpack_require__ (http://192.168.88.76:3000/static/js/bundle.js:94734:33)
at fn (http://192.168.88.76:3000/static/js/bundle.js:94968:21)
at ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.speech/ConnectionFactoryBase.js (http://192.168.88.76:3000/static/js/bundle.js:74036:83)
at ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.speech/ConnectionFactoryBase.js (http://192.168.88.76:3000/static/js/bundle.js:74036:83)
at ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.speech/ConnectionFactoryBase.js (http://192.168.88.76:3000/static/js/bundle.js:74036:83)

### Version

1.33.0 (Latest)

### What browser/platform are you seeing the problem on?

Node, Chrome, React

### Relevant log output

```shell
ERROR
Cannot access 'ConnectionFactoryBase' before initialization
ReferenceError: Cannot access 'ConnectionFactoryBase' before 
initialization
at Module.ConnectionFactoryBase (http://192.168.88.76:3000/static/js/bundle.js:74034:68)
at ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.speech/IntentConnectionFactory.js (http://192.168.88.76:3000/static/js/bundle.js:75615:94)<BR>at options.factory 
(http://192.168.88.76:3000/static/js/bundle.js:95311:31)
at __webpack_require__ (http://192.168.88.76:3000/static/js/bundle.js:94734:33)
at fn (http://192.168.88.76:3000/static/js/bundle.js:94968:21)
at ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.speech/Exports.js (http://192.168.88.76:3000/static/js/bundle.js:75422:85)
at options.factory (http://192.168.88.76:3000/static/js/bundle.js:95311:31)
at __webpack_require__ (http://192.168.88.76:3000/static/js/bundle.js:94734:33)
at fn (http://192.168.88.76:3000/static/js/bundle.js:94968:21)
at ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.speech/ConnectionFactoryBase.js (http://192.168.88.76:3000/static/js/bundle.js:74036:83)
at ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.speech/ConnectionFactoryBase.js (http://192.168.88.76:3000/static/js/bundle.js:74036:83)
at ./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.speech/ConnectionFactoryBase.js (http://192.168.88.76:3000/static/js/bundle.js:74036:83)
```

**Comment by glharper** [comment]
Hi @sorressean, there are intent recognition samples [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/index.html) embedded alongside speech recognition and translation. Pull out the parts relating to intent recognizer, and, if you're still running into issues, post the code you're having trouble with.
