### ISSUE TITLE
[Bug]: SDK Crashes

### ISSUE THREAD

**Issue by artem-morozyonok** [microsoft/cognitive-services-speech-sdk-js#820]
### What happened?

Hello, our Node.js backend application is using speech recognition functionality to convert audio from input stream captured on frontend side to transcribed text. 
Here is a configuration code:
```
import {
  AudioConfig,
  AudioInputStream,
  AudioStreamFormat,
  ConversationTranscriber,
  ProfanityOption,
  PushAudioInputStream,
  ServicePropertyChannel,
  SpeechConfig,
} from 'microsoft-cognitiveservices-speech-sdk';
....
const audioFormat = AudioStreamFormat.getDefaultInputFormat();
const stream = AudioInputStream.createPushStream(audioFormat);
const audioConfig = AudioConfig.fromStreamInput(stream);
const speechConfig = SpeechConfig.fromSubscription({key}, {region});
speechConfig.setServiceProperty('punctuation', 'explicit', ServicePropertyChannel.UriQueryParameter);
speechConfig.setProfanity(ProfanityOption.Raw);
const conversationTranscriber = new ConversationTranscriber(speechConfig, audioConfig);
```
The key line here is - `speechConfig.setServiceProperty('punctuation', 'explicit', ServicePropertyChannel.UriQueryParameter);` we need punctuation to be dictated, to achieve `comma` to be converted to `,` as well as some other punctuation options. But if user dictates `comma` or `period` two times in a row SDK crashes. 

### Version

1.36.0 (Latest)

### What browser/platform are you seeing the problem on?

Node

### Relevant log output

```shell
/{path}/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common/Stream.js:67
            throw new Error_js_1.InvalidOperationError("Stream closed");
                  ^

InvalidOperation: Stream closed
    at ChunkedArrayBufferStream.throwIfClosed (/{path}/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common/Stream.js:67:19)
    at ChunkedArrayBufferStream.writeStreamChunk (/{path}/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common/Stream.js:36:14)
    at ChunkedArrayBufferStream.writeStreamChunk (/{path}/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common/ChunkedArrayBufferStream.js:36:23)
    at PushAudioInputStreamImpl.write (/{path}/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/sdk/Audio/AudioInputStream.js:110:25)
```

**Comment by artem-morozyonok** [comment]
Found issue on our side, sorry for disturbing.
