### ISSUE TITLE
[Bug]: Deno incompatibility.

### ISSUE THREAD

**Issue by joshluongo** [microsoft/cognitive-services-speech-sdk-js#865]
### What happened?

While running the library in Deno you get an error relating to classic worker not being available.

Setting the workers type to `module` seems to fix this issue.

### Version

1.36.0 (Latest)

### Relevant log output

NotSupported: Classic workers are not supported.
    at createWorker (ext:runtime/11_workers.js:51:10)
    at new Worker (ext:runtime/11_workers.js:126:16)
    at Function.load (file:///Users/josh/Developer/Github/deno-ms-broken/node_modules/.deno/microsoft-cognitiveservices-speech-sdk@1.41.0/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common/Timeout.js:14:24)
    at Function.timers (file:///Users/josh/Developer/Github/deno-ms-broken/node_modules/.deno/microsoft-cognitiveservices-speech-sdk@1.41.0/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common/Timeout.js:83:44)
    at SpeechServiceRecognizer.Timeout.setTimeout [as privSetTimeout] (file:///Users/josh/Developer/Github/deno-ms-broken/node_modules/.deno/microsoft-cognitiveservices-speech-sdk@1.41.0/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common/Timeout.js:97:47)
    at file:///Users/josh/Developer/Github/deno-ms-broken/node_modules/.deno/microsoft-cognitiveservices-speech-sdk@1.41.0/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.speech/ServiceRecognizerBase.js:685:46
    at new Promise (<anonymous>)
    at SpeechServiceRecognizer.delay (file:///Users/josh/Developer/Github/deno-ms-broken/node_modules/.deno/microsoft-cognitiveservices-speech-sdk@1.41.0/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.speech/ServiceRecognizerBase.js:685:16)
    at readAndUploadCycle (file:///Users/josh/Developer/Github/deno-ms-broken/node_modules/.deno/microsoft-cognitiveservices-speech-sdk@1.41.0/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.speech/ServiceRecognizerBase.js:612:32)
    at Object.runMicrotasks (ext:core/01_core.js:672:26)

**Comment by xcaptain** [comment]
Same as bun. same code, successful when using node but failed when using bun
