### ISSUE TITLE
Rejecting a completed promise

### ISSUE THREAD

**Issue by ionTea** [microsoft/cognitive-services-speech-sdk-js#92]
An error in the speech recogniser causes our whole server to crash

It happens when network requests fail, to reproduce just try using speech recognition without an internet connection.

```
[App] node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common/src/common/Promise.ts:446
[App]                 throw new Error(`'Unhandled callback error: ${e}. InnerError: ${error}'`);
[App]                       ^
[App] Error: 'Unhandled callback error: Error: 'Cannot reject a completed promise'. InnerError: 'Unhandled callback error: Error: 'Cannot reject a completed promise'''
[App]     at Sink.executeErrorCallback (node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common/src/common/Promise.ts:446:23)
[App]     at Sink.executeSuccessCallback (node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common/src/common/Promise.ts:437:18)
[App]     at Sink.resolve (node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common/src/common/Promise.ts:390:18)
[App]     at Deferred.resolve (node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common/src/common/Promise.ts:349:23)
[App]     at WebSocket._this.privWebsocketClient.onclose (node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/src/common.browser/WebsocketMessageAdapter.ts:192:54)
[App]     at WebSocket.onClose (node_modules/ws/lib/event-target.js:124:16)
[App]     at WebSocket.emit (events.js:182:13)
[App]     at WebSocket.EventEmitter.emit (domain.js:442:20)
[App]     at WebSocket.emitClose (node_modules/ws/lib/websocket.js:184:12)
[App]     at ClientRequest.req.on (node_modules/ws/lib/websocket.js:555:15)
[App]     at ClientRequest.emit (events.js:187:15)
[App]     at ClientRequest.EventEmitter.emit (domain.js:442:20)
[App]     at TLSSocket.socketErrorListener (_http_client.js:391:9)
[App]     at TLSSocket.emit (events.js:182:13)
[App]     at TLSSocket.EventEmitter.emit (domain.js:442:20)
[App]     at emitErrorNT (internal/streams/destroy.js:82:8)
[App]     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
[App]     at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by rhurey** [comment]
Well, sorry you hit this problem.

I could use some help getting a local repro of the issue, though as I've been unsuccessful.

What version of the SDK are you using? Latest 1.7.0?
How did you remove the internet connection?
I've tried:
- Disable the machine adapter.
- Set the machine adapter to an invalid (for the actual LAN) IP.
- Put a bad DNS entry in a hosts file for the cloud endpoint.

**Comment by ionTea** [comment]
I simply disabled the wifi on my laptop.
The version used is
```
"microsoft-cognitiveservices-speech-sdk": "^1.7.0",
```

Here's some example code:
```
try {
  const pushStream = sdk.AudioInputStream.createPushStream();
  audio
    .on('data', arrayBuffer => {
      pushStream.write(arrayBuffer.slice());
    })
    .on('end', function() {
      pushStream.close();
    });

  const audioConfig = sdk.AudioConfig.fromStreamInput(pushStream);
  const speechConfig = sdk.SpeechConfig.fromSubscription(
    AZURE_API_KEY,
    AZURE_REGION,
  );
  speechConfig.speechRecognitionLanguage = LANGUAGE_TAG;

  const recognizer = new sdk.SpeechRecognizer(speechConfig, audioConfig);

  const text: string | undefined = await new Promise((resolve, reject) => {
    recognizer.recognizeOnceAsync(
      // Always calls the success callback, even on error?
      result => {
        if (result.text) {
          resolve(result.text);
        }
        recognizer.close();
      },
      (err: any) => {
        logger.error('Transcribe failed', {
          expected,
          message: err,
        });
        reject(err);
        recognizer.close();
      },
    );
  });
  return { text: text || '', status: text ? 'success' : 'failed' };
} catch (error) {
  // Can't catch the error
}

```

**Comment by haringummidi** [comment]
@rhurey 
I was facing the same issue, my service is sitting behind an proxy, but, our proxy do not support https. Java code for the same was actually working fine, with in the same proxy. But, node application throwing error with OCSP and code 400. So, started using ocsp_disable branch. Have configured IP using speechConfig.setProxy() method. and started using
 (But getting, (cancel) Reason: Error: Unable to contact server. StatusCode: 1000, undefined Reason: Exceeded maximum websocket connection idle duration(> 300000ms)

Later updated code with below line as advised in the info of the git branch, 
process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;  But, same error persists.

Please help!

**Comment by rhurey** [comment]
The ocsp_disable branch is a copy of what's in this PR: https://github.com/microsoft/cognitive-services-speech-sdk-js/pull/75

That PR failed all our tests when the disable flag was set, so it wasn't merged to master, and the author hasn't responded after submitting the PR.

The underlying problem you're hitting is that the JavaScript SDK requires an TLS connection to our cloud service. Are you trying to specify an endpoint directly and request ws:// for the protocol instead of wss://?

**Comment by haringummidi** [comment]
Hi, I have resolved the problem. Actually, i was integrating Cognitive service with IBM Voice gateway. But, ocsp_disable did not worked for me. But, SDK version 1.4 resolved the above said issue.

Sorry for late reply,  Thanks for your support.

**Comment by rodrigorodriguez** [comment]
@rhurey any news here? The same occurs in 1.12.0:

```
\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common\Promise.js:354
                    throw new Error("'Unhandled callback error: " + e + ". InnerError: " + error + "'");
                    ^

Error: 'Unhandled callback error: Error: 'Cannot reject a completed promise'. InnerError: 'Unhandled callback error: Error: 'Cannot reject a completed promise'''
    at Sink.executeErrorCallback (C:\Users\admin230489\Sources\BotServer\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common\Promise.js:354:27)
    at Sink.executeSuccessCallback (C:\Users\admin230489\Sources\BotServer\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common\Promise.js:345:23)
    at Sink.resolve (C:\Users\admin230489\Sources\BotServer\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common\Promise.js:306:23)    at Deferred.resolve (C:\Users\admin230489\Sources\BotServer\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common\Promise.js:277:28)
    at WebSocket._this.privWebsocketClient.onclose (C:\Users\admin230489\Sources\BotServer\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common.browser\WebsocketMessageAdapter.js:114:59)
    at WebSocket.onClose (C:\Users\admin230489\Sources\BotServer\node_modules\ws\lib\event-target.js:129:16)
    at WebSocket.emit (events.js:189:13)
    at WebSocket.emitClose (C:\Users\admin230489\Sources\BotServer\node_modules\ws\lib\websocket.js:184:12)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:189:13)
    at ClientRequest.emitAbortNT (_http_client.js:317:8)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Cc: @ph-nascimento

**Comment by oscholz** [comment]
@rodrigorodriguez Can you give us any additional information about what is going on when you hit this? if you can describe the end to end use case, that would help, too, and then tell us in which step you hit this.
I will close this issue until you get back to us. Please reactivate with the information. If you are in the browser when this is happening, please send us information from the developer console that shows what is happening as you hit this. 
Thank you for using the JS Speech SDK! We look forward to getting more info!
